### ISSUE TITLE
Wrong comment about cross platform

### ISSUE THREAD

**Issue by Eptick** [Bilal-io/Selenium-Screenshot-Script#1]
You have a comment here
https://github.com/Bilal-io/Selenium-Screenshot-Script/blob/2df2ce53a1cb1f8bebf4edfc9ef7255cbd2a610e/screenshot_headful_desktop.py#L1
That says that this will work on all system and it won't since you have hardcoded the path to the chromedriver here
https://github.com/Bilal-io/Selenium-Screenshot-Script/blob/2df2ce53a1cb1f8bebf4edfc9ef7255cbd2a610e/screenshot_headful_desktop.py#L7
People will get confused.

**Comment by Bilal-io** [comment]
Thank you @Eptick, you're right, fixed now.
